name 'lfisher47-aide'
version '0.0.1'
author 'lfisher47'
summary 'Aide STIG rule enforcement'
description 'Aide STIG rule enforcement'
license 'GNU GPL 2.0'
source 'git://github.com/lfisher47/puppet-aide'
project_page 'https://github.com/lfisher47/puppet-aide'
